sudo: required
dist: trusty

language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

script:
  - make build-libgraphio
  - make $CMD

env:
  matrix:
    - CC=gcc-5 CXX=g++-5 CMD="BASELINE=1 PAGERANK=1 build-graph-compute"
    - CC=gcc-5 CXX=g++-5 CMD="D0_BSP=1 PAGERANK=1 build-graph-compute"
    - CC=gcc-5 CXX=g++-5 CMD="D1_PRIO=1 PAGERANK=1 build-graph-compute"
    - CC=gcc-5 CXX=g++-5 CMD="D1_CHROM=1 PAGERANK=1 build-graph-compute"
    - CC=gcc-5 CXX=g++-5 CMD="D1_CHUNK=1 CHUNK_BITS=8 PAGERANK=1 build-graph-compute"
    - CC=gcc-5 CXX=g++-5 CMD="D1_PHASE=1 CHUNK_BITS=8 PAGERANK=1 build-graph-compute"
    - CC=gcc-5 CXX=g++-5 CMD="D1_NUMA=1 CHUNK_BITS=8 PAGERANK=1 build-graph-compute"
    - CC=gcc-5 CXX=g++-5 CMD="BASELINE=1 MASS_SPRING_DASHPOT=1 build-graph-compute"
    - CC=gcc-5 CXX=g++-5 CMD="D0_BSP=1 MASS_SPRING_DASHPOT=1 build-graph-compute"
    - CC=gcc-5 CXX=g++-5 CMD="D1_PRIO=1 MASS_SPRING_DASHPOT=1 build-graph-compute"
    - CC=gcc-5 CXX=g++-5 CMD="D1_CHROM=1 MASS_SPRING_DASHPOT=1 build-graph-compute"
    - CC=gcc-5 CXX=g++-5 CMD="D1_CHUNK=1 CHUNK_BITS=8 MASS_SPRING_DASHPOT=1 build-graph-compute"
    - CC=gcc-5 CXX=g++-5 CMD="D1_PHASE=1 CHUNK_BITS=8 MASS_SPRING_DASHPOT=1 build-graph-compute"
    - CC=gcc-5 CXX=g++-5 CMD="D1_NUMA=1 CHUNK_BITS=8 MASS_SPRING_DASHPOT=1 build-graph-compute"
